
MEASUREMENT_TIME = 60
NAMESPACE = "default"

GOLDPINGER = True
GOLDPINGER_IP = '127.0.0.1'
GOLDPINGER_PORT = 30080
GOLDPINGER_NAMESPACE = 'default'
GOLDPINGER_APP_NAME = 'goldpinger'

CLUSTERING = True
INITIAL_CLUSTER_LAYERS = []

MASTER_IP = "127.0.0.1"
RESULTS_DIR = 'simulations/temp/results/'
SPLITTING_CHAR = '-'
METADATA_PATH = ''
PODS_PATH = ''
NODES_PATH = ''
DELAY_MATRIX_PATH = ''
SCHEDULER_NAME = 'custom-scheduler'
MASTER_NAME = 'master'
PING_POD_IMAGE = 'ianneub/network-tools:latest'
